# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#   
#   1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
#   
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred divisors?

N = 500

find_factor = function (x) {
  if (x <= 3) { return (x) }
  for (i in 2:sqrt(x)) {
    if (x %% i == 0) {
      return (i)
    }
  }
  return (x)
}

f = function (x) {
  
  nth = 2
  prime_factors = c('1' = 0) # avoid checking if prime_factors is null
  divisors = 0
  
  while (divisors <= x) {
    
    nth = nth + 1
    prime_factors = c('1'=0)
    divisors = 1
    
    num = nth * (nth + 1) / 2 # nth triangular = n(n+1)/2
    while (num != 1) {
      f = as.character(find_factor(num))
      num = num / as.integer(f)
      if (is.na(prime_factors[f])) {
        prime_factors[f] = 1
      }
      else {
        prime_factors[f] = prime_factors[f] + 1
      }
    }
    
    for (i in names(prime_factors)) { # divisors = product of ((powers of primes) + 1)
      divisors = divisors * (prime_factors[i][[1]] + 1)
    }
  }
  
  return (nth * (nth + 1) / 2)
}

t = proc.time()
f(N)
proc.time() - t
