#!/usr/bin/env python

import time


# Problem:
# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

def num_distinct_powers(bases, expos):
    if len(bases) > 0 and len(expos) > 0:
        
        powers = []
        for base in bases:
            for expo in expos:
                powers.append(base**expo)

        return len(set(powers))


def main():
    print(num_distinct_powers(range(2, 101), range(2, 101)))

if __name__ == '__main__':
	start = time.time()
	main()
	print('Program runtime: {0:.3f}s'.format(time.time() - start))
